apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-beivubne
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-beivubne 
  name: go-beivubne
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-beivubne
    weight: 100 
